name: 'Setup Docs Environment'
description: 'Reusable action to set up documentation build environment'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
      shell: bash
    - run: npm run validate
      shell: bash
